inso/Models/EFContext.cs
namespace inso
{
    using global::inso.Models;
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration.Conventions;
    using System.Linq;
    namespace inso.Models
    {
        public class EFContext : DbContext
        {
            public DbSet<Pregunta> Pregunta { get; set; }
            public EFContext()
                : base("name=EFContext")
            {
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Conventions
                    .Remove<PluralizingTableNameConvention>();
                #region
                modelBuilder.Entity<Pregunta>()
                    .Property(x => x.pregunta)
                    .HasMaxLength(200)
                    .IsRequired();
                #endregion

                #region
                modelBuilder.Entity<Pregunta>()
                    .Property(x => x.opt1)
                    .HasMaxLength(200)
                    .IsRequired();
                #endregion


                #region
                modelBuilder.Entity<Pregunta>()
                    .Property(x => x.opt2)
                    .HasMaxLength(200)
                    .IsRequired();
                #endregion


                #region
                modelBuilder.Entity<Pregunta>()
                    .Property(x => x.opt3)
                    .HasMaxLength(200)
                    .IsRequired();
                #endregion


                #region
                modelBuilder.Entity<Pregunta>()
                    .Property(x => x.opt4)
                    .HasMaxLength(200)
                    .IsRequired();
                #endregion
            }

        }

        //public class MyEntity
        //{
        //    public int Id { get; set; }
        //    public string Name { get; set; }
        //}
    }
}

inso/Models/Pregunta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace inso.Models
{
    public class Pregunta
    {
        public int PreguntaId { get; set; }
        public string pregunta { get; set; }
        public string opt1 { get; set; }
        public string opt2 { get; set; }
        public string opt3 { get; set; }
        public string opt4 { get; set; }
        public string contador { get; set; }
    }
}

inso/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inso.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

inso/Controllers/MateController.cs
using inso.Servicios;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace inso.Controllers
{
    public class MateController : Controller
    {
        IPreguntaServices pregres;

        public MateController()
        {
            pregres = new PreguntaService();
        }
        // GET: Mate
        public ActionResult Index(int? pagina)
        {
            int pagtam = 1;
            int numpag= pagina ?? 1;
            var list = pregres.ReadPreg();
            return View(list.ToPagedList(numpag,pagtam));
        }

    }
}

inso/Controllers/SubMenyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inso.Controllers
{
    public class SubMenyController : Controller
    {
        // GET: SubMeny
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

inso/Controllers/ViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace inso.Controllers
{
    public class ViewController : Controller
    {
        // GET: View
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

inso/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

inso/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

inso/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

inso/Views/Mate/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<inso.Models.Pregunta>
<!doctype html>
<html>

<body onload="cuenta();">
    <div class="row">
        <div class="col-sm-4"></div>
    </div>
    <div class="row" id="alls">
        <div class="col-sm-4">
            <script language="javascript" src="~/Content/temporizador.js"></script>
            <link href="~/Content/bootstrap.css" rel="stylesheet" />
            <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
            <link href="~/Content/quiz.css" rel="stylesheet" />
            <link href="~/Content/b1.css" rel="stylesheet" />
            <div id="quizContainer" class="container">

                <table class="table" style="background-color:white">
                    @foreach (var item in Model)
                    {
                        <div id="contador" align="center" class="contador">
                            @Html.DisplayFor(modelItem => item.contador)
                        </div>
                        <tr>
                            <td id="question" class="question" style="font-size:30px;color:#000000">
                                @Html.DisplayFor(modelItem => item.pregunta)

                            </td>

                        </tr>
                        <tr>
                            <td class="option">
                                <input type="radio" name="option" value="1">
                                @Html.DisplayFor(modelItem => item.opt1, new { id = "opt1" })
                            </td>
                            <td class="option">
                                <input type="radio" name="option" value="2">
                                @Html.DisplayFor(modelItem => item.opt2, new { id = "opt2" })
                            </td>
                        </tr>
                        <tr>
                            <td class="option">
                                <input type="radio" name="option" value="3">
                                @Html.DisplayFor(modelItem => item.opt3, new { id = "opt3" })
                            </td>
                            <td class="option">
                                <input type="radio" name="option" value="4">
                                @Html.DisplayFor(modelItem => item.opt4, new { id = "opt4" })
                            </td>

                        </tr>

                    }
                </table>
                <button id="nextButton" class="next-btn" onclick="document.getElementById('img').style.display = '';
            document.getElementById('alls').style.backgroundColor = 'white'; document.getElementById('quizContainer').style.display='none';
		document.getElementById('result').style.display= ''; document.getElementById('Comprob').style.display='none';">Siguiente</button>
            </div>
            <div id="result" class="container result" style="display: none;color:#000000"></div>
            <label id="Comprob" class="lbrs" style="display: none"></label>
            <h1 id="hz" style="display: none"></h1>
            <div style="display:none" id="img">
                <img src="~/Content/aprobao.gif" width="70%" style="margin-top:30%;margin-left:115%" />
            </div>
            <div style="display:none" id="imgs">
                <img src="~/Content/reprobado.gif" width="70%" style="margin-top:30%;margin-left:115%" />
            </div>
            <div id="results" class="container result" style="display: none;color:#000000"></div>
        </div>
    </div>
</body>
</html>

@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))

<h5 style="color:black">Pregunta @Model.PageNumber de @Model.PageCount</h5>



                
     

inso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:black; display:none" id="navbar">
        <div class="container" style="background-color:black" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "View", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="background-color:black">
                <ul class="nav navbar-nav" >
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

inso/Views/SubMeny/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/cs1.css" />
   <script type="text/javascript">
       function crecer(x) {
           x.style.width = "52.5%";
       }

       function normal(x) {
           x.style.width = "51%";
       }

       function crec(x) {
           x.style.width = "46%";
       }

       function nor(x) {
           x.style.width = "44%";
       }
   </script>
</head>

<body onload=" document.getElementById('navbar').style.display = 'none';">
    <div style="background-color:aquamarine; height:20%; width:120%;  margin-left:-5%">
        <br /><br /><br /><br /><br /><br />
    </div>
   
    <div class="container" style="border: 50px solid white">

        <div style="background-color:white; float:right; width:40%; border:solid thin #000000">
            <img onmouseover="crecer(this)" onclick="window.location.href='/Mate/Index'" onmouseout="normal(this)" src="~/Content/15899.png" width="50%" style="float:right; margin-top:2%" />
            <h2 style="float:left; margin-top:28%; margin-left:5%; font-size:26px">MATEMATICA</h2>

        </div>

        <img src="~/Content/PiggygifWeb.gif" width="18%" style="margin-top:6%; margin-left:2%" /> 
      

        <div style="background-color:white; float:left; width:39%; border:solid thin #000000">
            <img onmouseover="crec(this)" onclick="window.location.href='/Mate/Index'" onmouseout="nor(this)" src="~/Content/img_leyendo.png" width="44%" height="20%" style="float:left;margin-top:2%" />
            <h2 style="float:right; margin-top:28%; margin-right:13%">LENGUAJE</h2>

        </div>

    </div>
</body>
</html>

inso/Views/View/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/cs1.css" />
    <script>
        function move() {
            var elem = document.getElementById("pb");
            var width = 1;
            var id = setInterval(frame, 110);
            document.getElementById('bar').style.display = '';
            document.getElementById('btn-jg').style.display = 'none';
            function frame() {
                if (width == 101) {
                    window.location.href = "/SubMeny/Index";
                }

                if (width > 100) {
                    clearInterval(id);
                } else {
                    width = width + 4;
                    elem.style.width = width + '%';
                }

                
                
            }
        }
    </script>
</head>

<body onload=" document.getElementById('bar').style.display = 'none'; document.getElementById('navbar').style.display = 'none';">
    <div style="background-color:aquamarine; height:20%; width:120%;  margin-left:-5%">
        <br /><br /><br /><br /><br /><br />
        </div>
    <div id="cnt" class="cnt" >
        <h2 style="margin-top:5%; margin-left:39.5%; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"><strong>
    <span style="color:crimson; font-size:40px">M</span><span style="color:cornflowerblue; font-size:34px">Y</span>
    <span style="color:darkorchid; font-size:41px">F</span><span style="color:darkorange; font-size:36px">I</span><span style="color:chartreuse; font-size:37px">R</span><span style="color:deepskyblue; font-size:40px">S</span><span style="color:fuchsia; font-size:36px">T</span>
    <span style="color:chocolate; font-size:38px">G</span><span style="color:cyan; font-size:36px">A</span><span style="color:chartreuse; font-size:36px">M</span><span style="color:chartreuse; font-size:40px">E</span>
</strong> </h2>
    </div>
        <div class="container" style="width:100%">
            <table align="center">
                <tr>
                    <td>
                        <img src="~/Content/RedAnimationLoop.gif" width="25%" style="margin-left:37.5%;margin-top:6%" /> <br /><br />

                    </td>
                </tr>
            </table>
            <div class="progress" style="width:30%; margin-left:35%" id="bar">
                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:0%" id="pb">
                </div>
            </div>
            <table align="center">
                <tr>
                    <td>
                        <button type="submit" onclick="move();" id="btn-jg" class="btn-jg">JUGAR</button>
                        <br /><br />
                    </td>
                </tr>
            </table>

        </div>
    
</body>
</html>